//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentBookApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Comment
    {
        [Key]
        public int Id { get; set; }

        [Required] //this makes sure the text in the comment is required
        [StringLength(200)] //this adds a character length to a comment
        public string Text { get; set; }

        [Required]
        public int PostId { get; set; }

        //[Required]
        public int AuthorId { get; set; }

        //[Required]
        public string AuthorName { get; set; }

        [Required]
        public System.DateTime Date { get; set; }

        public int Author_Id { get; set; }
    
        public virtual User User { get; set; }
        public virtual Post Post { get; set; }
    }
}
