//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentBookApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        //this models code was adpated from https://www.youtube.com/watch?v=xBS9FMF2NFM&list=PLdUi92csWFpKWs_JMTaSv8_h7AfRMjJ4Z&index=6
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User() //this is a constructor
        {
            this.Comments = new HashSet<Comment>();
            this.Posts = new HashSet<Post>();
        }

        public int UserID { get; set; }

        [Required(ErrorMessage = "This Field is Required!")] //this indicates to the user that this field is required
        public string FirstName { get; set; }

        [Required(ErrorMessage = "This Field is Required!")] //this indicates to the user that this field is required
        public string Surname { get; set; }

        [Required(ErrorMessage = "This Field is Required!")] //this indicates to the user that this field is required
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime DateOfBirth { get; set; }

        [Required(ErrorMessage = "This Field is Required!")] //this indicates to the user that this field is required
        [RegularExpression(@"([0-9])+@(live.wcs.ac.uk)$", ErrorMessage = "Please enter a valid student Email Address")]
        public string EmailID { get; set; }

        [Required(ErrorMessage = "This Field is Required!")] //this indicates to the user that this field is required
        [DataType(DataType.Password)] //this makes sure that this is a password
        [MinLength(6, ErrorMessage = "Please enter a min of 6 characters or more")] //this makes sure that the users password is 6 characters or more
        public string Password { get; set; }

        [Required(ErrorMessage = "This Field is Required!")] //this indicates to the user that this field is required
        [DataType(DataType.Password)] //this makes that the confirm password is a password
        [DisplayName("Confirm Password")]
        [Compare("Password", ErrorMessage = "Password and Confirm Password do no match")] //this comapres the password and confirm password and makes sure that it matches
        public string ConfirmPassword { get; set; }

        public string College { get; set; }
        public string Course { get; set; }
        public virtual ICollection<Comment> Comments { get; set; } //this is a foreign key class in the database and links it to the comment table
        public virtual ICollection<Post> Posts { get; set; } //this is foreign key class in the database and links it to the posts table
        public virtual UserRole UserRole { get; set; }
    }
}
